{% set name = "poetry-dynamic-versioning-plugin" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry-dynamic-versioning-plugin-{{ version }}.tar.gz
  sha256: 9d6b22973e79f499a7a9a2e22af479b24e9d6bc614a1cf3344cb0f3847fc3063

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - dunamai >=1.12.0,<2.0.0
    - jinja2 >=2.11.1,<4
    - poetry >=1.2.0,<2.0.0
    - python >={{ python_min }}
    - tomlkit >=0.4

test:
  imports:
    - poetry_dynamic_versioning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_file: LICENSE
  description: |
    **Conda-forge notes:** If you are using this in a conda-forge package and the source URL is PyPI,
    it is possible that this plugin is unable to set the version correctly, as a VCS tag is generally required.
    
    In order to override the plugin and fix this behaviour, add the following to the `build:` section if your meta.yml:
{% raw %}
    ```yml
    script_env:
      - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
    ```
{% endraw %}
    This will pull in the version defined in your meta.yml.

extra:
  recipe-maintainers:
    - BastianZim
